using System;
using System.Collections.Concurrent;
using System.ComponentModel;
using System.Runtime.InteropServices;

namespace WheelFix
{
    internal sealed class NativeMouseHook : IDisposable
    {
        private const int WhMouseLl = 14;
        private const int WmMouseWheel = 0x020A;
        private const uint LlmhfInjected = 0x00000001;

        private readonly WheelFilterCore _filter;
        private readonly NativeMethods.LowLevelMouseProc _callback;
        private readonly ConcurrentQueue<WheelTraceEvent> _traceEvents;
        private IntPtr _hookHandle;

        public NativeMouseHook(WheelFilterCore filter)
        {
            if (filter == null)
            {
                throw new ArgumentNullException("filter");
            }

            _filter = filter;
            _callback = HookCallback;
            _traceEvents = new ConcurrentQueue<WheelTraceEvent>();
            _hookHandle = IntPtr.Zero;
        }

        public bool TryDequeueTrace(out WheelTraceEvent traceEvent)
        {
            return _traceEvents.TryDequeue(out traceEvent);
        }

        public void Start()
        {
            if (_hookHandle != IntPtr.Zero)
            {
                return;
            }

            IntPtr moduleHandle = NativeMethods.GetModuleHandle(null);
            _hookHandle = NativeMethods.SetWindowsHookEx(
                WhMouseLl, _callback, moduleHandle, 0U);

            if (_hookHandle == IntPtr.Zero)
            {
                throw new Win32Exception(Marshal.GetLastWin32Error(),
                    L.Text(
                        "Windows rejected the global mouse hook.",
                        "Windows non ha accettato l'hook globale del mouse."));
            }
        }

        public void Dispose()
        {
            if (_hookHandle != IntPtr.Zero)
            {
                NativeMethods.UnhookWindowsHookEx(_hookHandle);
                _hookHandle = IntPtr.Zero;
            }

            GC.SuppressFinalize(this);
        }

        private IntPtr HookCallback(int nCode, IntPtr wParam, IntPtr lParam)
        {
            if (nCode >= 0 && wParam.ToInt32() == WmMouseWheel)
            {
                NativeMethods.MsLlHookStruct data =
                    (NativeMethods.MsLlHookStruct)Marshal.PtrToStructure(
                        lParam, typeof(NativeMethods.MsLlHookStruct));

                // Do not modify events generated by accessibility software,
                // remote-control tools or other applications.
                if ((data.Flags & LlmhfInjected) == 0U)
                {
                    int delta = unchecked((short)(data.MouseData >> 16));
                    int replayDelta;
                    WheelFilterDecision decision =
                        _filter.Process(delta, out replayDelta);

                    if (decision == WheelFilterDecision.Replay &&
                        !NativeMethods.SendWheelInput(replayDelta))
                    {
                        decision = WheelFilterDecision.ReplayFailed;
                    }

                    _traceEvents.Enqueue(new WheelTraceEvent(
                        data.Time, delta, decision, replayDelta));

                    if (decision == WheelFilterDecision.Block ||
                        decision == WheelFilterDecision.Replay)
                    {
                        return new IntPtr(1);
                    }
                }
            }

            return NativeMethods.CallNextHookEx(_hookHandle, nCode, wParam, lParam);
        }
    }

    internal struct WheelTraceEvent
    {
        internal readonly uint Timestamp;
        internal readonly int Delta;
        internal readonly WheelFilterDecision Decision;
        internal readonly int ReplayDelta;

        internal WheelTraceEvent(
            uint timestamp,
            int delta,
            WheelFilterDecision decision,
            int replayDelta)
        {
            Timestamp = timestamp;
            Delta = delta;
            Decision = decision;
            ReplayDelta = replayDelta;
        }
    }

    internal static class NativeMethods
    {
        private const uint InputMouse = 0U;
        private const uint MouseEventWheel = 0x0800U;

        internal delegate IntPtr LowLevelMouseProc(
            int nCode, IntPtr wParam, IntPtr lParam);

        [StructLayout(LayoutKind.Sequential)]
        internal struct Point
        {
            internal int X;
            internal int Y;
        }

        [StructLayout(LayoutKind.Sequential)]
        internal struct MsLlHookStruct
        {
            internal Point Pt;
            internal uint MouseData;
            internal uint Flags;
            internal uint Time;
            internal UIntPtr ExtraInfo;
        }

        [StructLayout(LayoutKind.Sequential)]
        internal struct Input
        {
            internal uint Type;
            internal InputUnion Data;
        }

        [StructLayout(LayoutKind.Explicit)]
        internal struct InputUnion
        {
            [FieldOffset(0)]
            internal MouseInput Mouse;
        }

        [StructLayout(LayoutKind.Sequential)]
        internal struct MouseInput
        {
            internal int Dx;
            internal int Dy;
            internal uint MouseData;
            internal uint Flags;
            internal uint Time;
            internal UIntPtr ExtraInfo;
        }

        internal static bool SendWheelInput(int delta)
        {
            Input input = new Input();
            input.Type = InputMouse;
            input.Data.Mouse.MouseData = unchecked((uint)delta);
            input.Data.Mouse.Flags = MouseEventWheel;
            return SendInput(1U, ref input, Marshal.SizeOf(typeof(Input))) == 1U;
        }

        [DllImport("user32.dll", SetLastError = true)]
        internal static extern IntPtr SetWindowsHookEx(
            int idHook,
            LowLevelMouseProc callback,
            IntPtr moduleHandle,
            uint threadId);

        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        internal static extern bool UnhookWindowsHookEx(IntPtr hookHandle);

        [DllImport("user32.dll")]
        internal static extern IntPtr CallNextHookEx(
            IntPtr hookHandle,
            int nCode,
            IntPtr wParam,
            IntPtr lParam);

        [DllImport("user32.dll", SetLastError = true)]
        private static extern uint SendInput(
            uint inputCount,
            ref Input inputs,
            int inputSize);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        internal static extern IntPtr GetModuleHandle(string moduleName);

    }
}
